logging_level: DEBUG

scenario:
  clusters: [37, 100]
  opts: [2H]
  model: [transport, lossless, lossy-3, lossy-8]
  slack: [distributed, regular]

additional_s_nom: 6800
s_nom_factor: 4
links_p_nom_max: 20000

solving:
  options:
    formulation: kirchhoff
    load_shedding: true
    noisy_costs: true
    clip_p_max_pu: 0.01
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-4
    AggFill: 0
    PreDual: 0
    BarHomogeneous: 1
    GURO_PAR_BARDENSETHRESH: 200
    # ScaleFlag: 2
    # NumericFocus: 2
