version: 0.1
tutorial: false
logging_level: INFO

summary_dir: results

scenario:
  sectors: [E]
  simpl: ['']
  ll: ['copt']
  clusters: [37, 100]
  opts: [Co2L-3H]
  loss: ['cosine']
  network: ['elec']

countries: ['DE'] 

snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  closed: 'left' # end is not inclusive


solving:
  options:
    formulation: angles
    load_shedding: true
    noisy_costs: true
    min_iterations: 3
    max_iterations: 5
    clip_p_max_pu: 0.01
    #nhours: 10
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-4
    AggFill: 0
    PreDual: 0
    NumericFocus: 2
    BarHomogeneous: 1
    ScaleFlag: 2
    GURO_PAR_BARDENSETHRESH: 200
  # solver:
  #   name: cplex
  #   threads: 4
  #   lpmethod: 4 # barrier
  #   solutiontype: 2 # non basic solution, ie no crossover
  #   barrier_convergetol: 1.e-5
  #   feasopt_tolerance: 1.e-6

plotting:
  map:
    figsize: [7, 7]
    boundaries: [-10.2, 29, 35,  72]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3

  costs_max: 800
  costs_threshold: 1

  energy_max: 15000.
  energy_min: -10000.
  energy_threshold: 50.

  vre_techs: ["onwind", "offwind-ac", "offwind-dc", "solar", "ror"]
  conv_techs: ["OCGT", "CCGT", "Nuclear", "Coal"]
  storage_techs: ["hydro+PHS", "battery", "H2"]
  load_carriers: ["AC load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"] 
  tech_colors:
    "onwind" : "#235ebc"
    "onshore wind" : "#235ebc"
    'offwind' : "#6895dd"
    'offwind-ac' : "#6895dd"
    'offshore wind' : "#6895dd"
    'offshore wind ac' : "#6895dd"
    'offwind-dc' : "#74c6f2"
    'offshore wind dc' : "#74c6f2"
    "hydro" : "#08ad97"
    "hydro+PHS" : "#08ad97"
    "PHS" : "#08ad97"
    "hydro reservoir" : "#08ad97"
    'hydroelectricity' : '#08ad97'
    "ror" : "#4adbc8"
    "run of river" : "#4adbc8"
    'solar' : "#f9d002"
    'solar PV' : "#f9d002"
    'solar thermal' : '#ffef60'
    'biomass' : '#0c6013'
    'solid biomass' : '#06540d'
    'biogas' : '#23932d'
    'waste' : '#68896b'
    'geothermal' : '#ba91b1'
    "OCGT" : "#d35050"
    "OCGT marginal" : "#d35050"
    "OCGT-heat" : "#d35050"
    "gas boiler" : "#d35050"
    "gas boilers" : "#d35050"
    "gas boiler marginal" : "#d35050"
    "gas-to-power/heat" : "#d35050"
    "gas" : "#d35050"
    "natural gas" : "#d35050"
    "CCGT" : "#b20101"
    "CCGT marginal" : "#b20101"
    "Nuclear" : "#ff9000"
    "Nuclear marginal" : "#ff9000"
    "nuclear" : "#ff9000"
    "coal" : "#707070"
    "Coal" : "#707070"
    "Coal marginal" : "#707070"
    "lignite" : "#9e5a01"
    "Lignite" : "#9e5a01"
    "Lignite marginal" : "#9e5a01"
    "Oil" : "#262626"
    "oil" : "#262626"
    "H2" : "#ea048a"
    "hydrogen storage" : "#ea048a"
    "Sabatier" : "#a31597"
    "methanation" : "#a31597"
    "helmeth" : "#a31597"
    "DAC" : "#d284ff"
    "co2 stored" : "#e5e5e5"
    "CO2 sequestration" : "#e5e5e5" 
    "battery" : "#b8ea04"
    "battery storage" : "#b8ea04"
    "Li ion" : "#b8ea04"
    "BEV charger" : "#e2ff7c"
    "V2G" : "#7a9618"
    "transport fuel cell" : "#e884be"
    "retrofitting" : "#e0d6a8"
    "building retrofitting" : "#e0d6a8"
    "heat pumps" : "#ff9768" 
    "heat pump" : "#ff9768"
    "air heat pump" : "#ffbea0"
    "ground heat pump" : "#ff7a3d"
    "power-to-heat" : "#a59e7c"
    "power-to-gas" : "#db8585"
    "power-to-liquid" : "#a9acd1"
    "Fischer-Tropsch" : "#a9acd1"
    "resistive heater" : "#aa4925"
    "water tanks" : "#401f75"
    "hot water storage" : "#401f75"
    "hot water charging" : "#351c5e"
    "hot water discharging" : "#683ab2"
    "CHP" : "#d80a56"
    "CHP heat" : "#d80a56"
    "CHP electric" : "#d80a56"
    "district heating" : "#93864b"
    "Ambient" : "#262626"
    "Electric load" : "#f9d002"
    "electricity" : "#f9d002"
    "Heat load" : "#d35050"
    "heat" : "#d35050"
    "Transport load" : "#235ebc"
    "transport" : "#235ebc"
    "lines" : "#70af1d"
    "transmission lines" : "#70af1d"
    "AC-AC" : "#70af1d"
    "AC line" : "#70af1d"
    "links" : "#8a1caf"
    "HVDC links" : "#8a1caf"
    "DC-DC" : "#8a1caf"
    "DC link" : "#8a1caf"
  nice_names:
    OCGT: "Open-Cycle Gas"
    CCGT: "Combined-Cycle Gas"
    offwind-ac: "Offshore Wind (AC)"
    offwind-dc: "Offshore Wind (DC)"
    onwind: "Onshore Wind"
    battery: "Battery Storage"
    H2: "Hydrogen Storage"
    lines: "Transmission lines"
    ror: "Run of river"
  nice_names_n:
    OCGT: "Open-Cycle\nGas"
    CCGT: "Combined-Cycle\nGas"
    offwind-ac: "Offshore\nWind (AC)"
    offwind-dc: "Offshore\nWind (DC)"
    onwind: "Onshore\nWind"
    battery: "Battery\nStorage"
    H2: "Hydrogen\nStorage"
    lines: "Transmission\nlines"
    ror: "Run of\nriver"
    
