logging_level: INFO

scenario:
  clusters: [100]
  opts: [2H]
  model: [transport, lossless-0, lossless-3, lossy-5, lossy-8]
  slack: [distributed, regular]

lines:
  s_nom_add: 10000
  s_nom_factor: 2

links:
  p_nom_max: 20000
  efficiency_per_length: 3.e-5

solving:
  options:
    min_iterations: 2
    max_iteratoins: 3
    formulation: kirchhoff
    load_shedding: true
    noisy_costs: false
    clip_p_max_pu: 0.01
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-3
    FeasibilityTol: 1.e-3
    AggFill: 0
    PreDual: 0
    BarHomogeneous: 1
    GURO_PAR_BARDENSETHRESH: 200
    # ResultFile: "model.ilp"
    # ScaleFlag: 2
    # NumericFocus: 2
