logging_level: INFO

scenario:
  clusters: [150]
  opts: [2H]
  model:
    [
      transport,
      lossytransport,
      lossless-0,
      lossless-3,
      lossy-3-0,
      lossy-5-0,
      lossy-3-3,
      lossy-5-3,
    ]
  slack: [distributed]

lines:
  s_nom_add: 5000
  s_nom_factor: 2
  s_max_pu: 0.7
  loss_per_length: 5.e-5 # only applies to lossy transport model

links:
  p_nom_max: 16000
  loss_per_length: 3.e-5

solving:
  options:
    min_iterations: 3
    max_iterations: 3
    formulation: kirchhoff
    load_shedding: true
    noisy_costs: false
    clip_p_max_pu: 0.01
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-4
    FeasibilityTol: 1.e-4
    AggFill: 0
    PreDual: 0
    BarHomogeneous: 1
    GURO_PAR_BARDENSETHRESH: 200
    # ResultFile: "model.ilp"
    # ScaleFlag: 2
    # NumericFocus: 2
