logging_level: DEBUG

scenario:
  clusters: [37, 100]
  opts: [2H]
  loss: [cosine, square]
  slack: [distributed, regular]

additional_s_nom: 6800
links_p_nom_max: 10000

solving:
  options:
    formulation: angles
    load_shedding: true
    noisy_costs: false
    min_iterations: 1
    max_iterations: 1
    clip_p_max_pu: 0.01
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-4
    AggFill: 0
    PreDual: 0
    BarHomogeneous: 1
    GURO_PAR_BARDENSETHRESH: 200
    # ScaleFlag: 2
    # ResultFile: model.ilp
    # NumericFocus: 2
