logging_level: INFO

scenario:
  ll: [copt]
  clusters: [37, 100]
  opts: [2H]
  loss: [cosine, lldc]
  slack: [distributed, regular]

additional_s_nom: 6800
links_p_nom_max: 10000

solving:
  options:
    formulation: angles
    load_shedding: true
    noisy_costs: false
    min_iterations: 1
    max_iterations: 1
    clip_p_max_pu: 0.01
  solver:
    name: gurobi
    threads: 4
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-5
    FeasibilityTol: 1.e-4
    AggFill: 0
    PreDual: 0
    NumericFocus: 2
    BarHomogeneous: 1
    ScaleFlag: 2
    GURO_PAR_BARDENSETHRESH: 200
  # solver:
  #   name: cplex
  #   threads: 4
  #   lpmethod: 4 # barrier
  #   solutiontype: 2 # non basic solution, ie no crossover
  #   barrier_convergetol: 1.e-5
  #   feasopt_tolerance: 1.e-6
